### ISSUE TITLE
WMP v1.2 release checklist

### ISSUE THREAD

**Issue by zd-zero** [zd-zero/waifu-motivator-plugin#136]
- [x] Bump version
- [x] Update screenshots with gifs and consistent LAF
  - [x] Update [README](https://github.com/zd-zero/waifu-motivator-plugin/blob/master/README.md) images
  - [x] Update images for [marketplace](https://plugins.jetbrains.com/plugin/13381-waifu-motivator) 
  - [x] Update the plugin screenshot usage from recently published plugin
- [x] New README section for new features
- [x] Update CHANGELOG content
- [x] Update welcome dialog content
- [x] Tag the commit with v1.2
- [x] Publish the plugin to the Marketplace

**Comment by Unthrottled** [comment]
This is done, isn't it?
