### ISSUE TITLE
WMP v1.3 Release Checklist

### ISSUE THREAD

**Issue by Unthrottled** [zd-zero/waifu-motivator-plugin#201]
- [x] Update README
- [x] Update CHANGELOG
- [x] Update Welcome Dialog Message
- [x] Create GitHub release on master to publish to Marketplace
- [x] Upload new demo to Marketplace once published

**Comment by Unthrottled** [comment]
@zd-zero I can take care of all of the documentation stuff.

**Comment by Unthrottled** [comment]
The changelog needs to be updated with the date that this was released.

**Comment by Unthrottled** [comment]
![It's happening](https://media.giphy.com/media/5mBE2MiMVFITS/giphy.gif)
